module.exports = {
  targets: 'defaults, not ie <= 11',
  presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-flow'],
  sourceMaps: 'inline',
  retainLines: true,
  plugins: [
    ['polyfill-corejs3', { method: 'usage-global' }],
    ['polyfill-regenerator', { method: 'usage-global' }],
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-json-strings',
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-logical-assignment-operators',
    '@babel/plugin-proposal-optional-chaining',
    [
      '@babel/plugin-proposal-pipeline-operator',
      {
        proposal: 'minimal',
      },
    ],
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-do-expressions',
  ],
  ignore: ['node_modules', 'build', 'download'],
};
